=== CryptoMeerkat/Software-Performance-Cockpit/org.sopeco.engine/src/org/sopeco/engine/model/SoPeCoScenarioDefinitionSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.sopeco.org/SoPeCoScenarioDefinitionSchema"
	xmlns:tns="http://www.sopeco.org/SoPeCoScenarioDefinitionSchema"
	elementFormDefault="qualified">

	<element name="scenario" type="tns:ScenarioDefinition"></element>

	<complexType name="ScenarioDefinition">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<element name="measurementSpecification" type="tns:MeasurementSpecification"
				maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>


	<complexType name="MeasurementSpecification">
		<sequence>
			<element name="experimentSeries" type="tns:ExperimentSeriesDefinition"
				maxOccurs="unbounded" minOccurs="1">
			</element>
			<element name="initializationAssignments" type="tns:ConstantValueAssignment"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="ExperimentSeriesDefinition">
		<all>
			<element name="explorationStrategy" type="tns:ExplorationStrategy"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="terminationConditions" type="tns:ExperimentTerminationCondition" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="experimentSeriesPreparation" maxOccurs="1"
				minOccurs="0">
				<complexType>
					<sequence>
						<element name="constantAssignment" type="tns:ConstantValueAssignment"
							maxOccurs="unbounded" minOccurs="0">
						</element>
					</sequence>
				</complexType>
			</element>
			<element name="experimentSeriesExecution" maxOccurs="1"
				minOccurs="1">
				<complexType>
					<sequence>
						<element name="constantAssignment" type="tns:ConstantValueAssignment"
							maxOccurs="unbounded" minOccurs="0">
						</element>
						<element name="dynamicAssignment" type="tns:DynamicValueAssignment"
							maxOccurs="unbounded" minOccurs="0">
						</element>
					</sequence>
				</complexType>
			</element>
		</all>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>



	<complexType name="ConstantValueAssignment">
		<attribute name="parameter" type="string" use="required"></attribute>
		<attribute name="value" type="string" use="required"></attribute>
	</complexType>


	<complexType name="DynamicValueAssignment">

		<sequence>
			<element name="config" type="tns:ConfigurationNode"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="parameter" type="string" use="required"></attribute>

	</complexType>


	<complexType name="ConfigurationNode">
		<attribute name="key" type="string" use="required"></attribute>
		<attribute name="value" type="string" use="required"></attribute>
	</complexType>

	<complexType name="ExtensibleElement">
		<sequence>
			<element name="config" type="tns:ConfigurationNode"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="AnalysisConfiguration">
		<complexContent>
			<extension base="tns:ExtensibleElement">
				<sequence>
					<element name="dependentParameter" type="string" maxOccurs="unbounded"
						minOccurs="0">
					</element>
					<element name="independentParameter" type="string"
						maxOccurs="unbounded" minOccurs="0"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="ExplorationStrategy">
		<complexContent>
			<extension base="tns:ExtensibleElement">
				<sequence>
					<element name="analysisConfig" type="tns:AnalysisConfiguration"
						maxOccurs="unbounded" minOccurs="0"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>



	<complexType name="ExperimentTerminationCondition">
		<sequence>
			<element name="condition" type="tns:ExtensibleElement" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
	</complexType>
</schema>

=== CryptoMeerkat/Software-Performance-Cockpit/org.sopeco.runner/rsc-test/testScenario.xml
<?xml version="1.0" encoding="UTF-8"?>
<scenario name="unitTestScenario" xmlns="http://www.sopeco.org/SoPeCoScenarioDefinitionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sopeco.org/SoPeCoScenarioDefinitionSchema http://www.sopeco.org/xsd/SoPeCoScenarioDefinitionSchema.xsd">
	<measurementSpecification name="unitTestSpec">

		<experimentSeries name="unitTestSeries">


			<terminationConditions>
				<condition name="Number of Repetitions">
					<config key="repetitions" value="2" />
				</condition>
			</terminationConditions>

			<experimentSeriesPreparation>
				<constantAssignment value="2" parameter="prepare.prepareParameter" />
			</experimentSeriesPreparation>


			<experimentSeriesExecution>
				<constantAssignment value="3" parameter="test.input.inputParameter" />

				<dynamicAssignment name="Linear Numeric Variation" parameter="test.input.inputParameter2">
					<config key="min" value="1" />
					<config key="max" value="2" />
					<config key="step" value="1" />
				</dynamicAssignment>
			</experimentSeriesExecution>

			<explorationStrategy name="Full Exploration Strategy" />

		</experimentSeries>

		<initializationAssignments value="1" parameter="init.initParameter" />
	</measurementSpecification>


</scenario>
